<?php

namespace Proxies\__CG__\PrintBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Pdfmerge extends \PrintBundle\Entity\Pdfmerge implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'PrintBundle\\Entity\\Pdfmerge' . "\0" . 'id', '' . "\0" . 'PrintBundle\\Entity\\Pdfmerge' . "\0" . 'name', '' . "\0" . 'PrintBundle\\Entity\\Pdfmerge' . "\0" . 'marge', '' . "\0" . 'PrintBundle\\Entity\\Pdfmerge' . "\0" . 'nbpage', '' . "\0" . 'PrintBundle\\Entity\\Pdfmerge' . "\0" . 'width', '' . "\0" . 'PrintBundle\\Entity\\Pdfmerge' . "\0" . 'height', '' . "\0" . 'PrintBundle\\Entity\\Pdfmerge' . "\0" . 'pdflist');
        }

        return array('__isInitialized__', '' . "\0" . 'PrintBundle\\Entity\\Pdfmerge' . "\0" . 'id', '' . "\0" . 'PrintBundle\\Entity\\Pdfmerge' . "\0" . 'name', '' . "\0" . 'PrintBundle\\Entity\\Pdfmerge' . "\0" . 'marge', '' . "\0" . 'PrintBundle\\Entity\\Pdfmerge' . "\0" . 'nbpage', '' . "\0" . 'PrintBundle\\Entity\\Pdfmerge' . "\0" . 'width', '' . "\0" . 'PrintBundle\\Entity\\Pdfmerge' . "\0" . 'height', '' . "\0" . 'PrintBundle\\Entity\\Pdfmerge' . "\0" . 'pdflist');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Pdfmerge $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrientaion($orientaion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrientaion', array($orientaion));

        return parent::setOrientaion($orientaion);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrientaion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrientaion', array());

        return parent::getOrientaion();
    }

    /**
     * {@inheritDoc}
     */
    public function setMarge($marge)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarge', array($marge));

        return parent::setMarge($marge);
    }

    /**
     * {@inheritDoc}
     */
    public function getMarge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarge', array());

        return parent::getMarge();
    }

    /**
     * {@inheritDoc}
     */
    public function setWidth($width)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWidth', array($width));

        return parent::setWidth($width);
    }

    /**
     * {@inheritDoc}
     */
    public function getWidth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWidth', array());

        return parent::getWidth();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeight($height)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeight', array($height));

        return parent::setHeight($height);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeight', array());

        return parent::getHeight();
    }

    /**
     * {@inheritDoc}
     */
    public function addPdflist(\PrintBundle\Entity\pdflist $pdflist)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPdflist', array($pdflist));

        return parent::addPdflist($pdflist);
    }

    /**
     * {@inheritDoc}
     */
    public function removePdflist(\PrintBundle\Entity\pdflist $pdflist)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePdflist', array($pdflist));

        return parent::removePdflist($pdflist);
    }

    /**
     * {@inheritDoc}
     */
    public function getPdflist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPdflist', array());

        return parent::getPdflist();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbpage($nbpage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbpage', array($nbpage));

        return parent::setNbpage($nbpage);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbpage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbpage', array());

        return parent::getNbpage();
    }

}
